<?php
//this file is used to initiate scraping and posting of a single URL

require_once plugin_dir_path(__DIR__) . '/vendor/autoload.php';
require_once plugin_dir_path(__DIR__) . '/includes/utilities.php';


function getScrapedData($sourceConfiguration, $url = null) {
    require_once plugin_dir_path(__DIR__) . '/includes/classes/clsScrapeWebsite.php';
    $scraper = new ScrapaWebsite();

    //preapare args for scraping
    $websiteConfig = [
        'baseUrl' => $sourceConfiguration['baseUrl'],
        'selectors' => [
            'catPageLastArticle' => stripslashes($sourceConfiguration['catPageLastArticle']),
            'title' => stripslashes($sourceConfiguration['title']),
            'content' => stripslashes($sourceConfiguration['content']),
            'imageUrl' => stripslashes(stripslashes($sourceConfiguration['imageUrl'])),
            'newsLabelSel' => stripslashes($sourceConfiguration['newsLabelSel']),
            'newsLabelText' => stripslashes($sourceConfiguration['newsLabelText'])
        ],
        'defaultImageCredit' => stripslashes($sourceConfiguration['newsLabelText'])
    ];

    $scrapedData = $scraper->scrapeWebsite($websiteConfig, $url);
    return $scrapedData;
}


//return
function runSingleAutoPost($singleSource, $url = null) {
    my_second_log('INFO', 'START WITH SOURCE: ' . $singleSource['baseUrl']);
    
    $scrapedData = getScrapedData($singleSource, $url); //return scraped data

    if($scrapedData == null) {
        return null;
    }
    else {

        if($url) { //if its From Url
            $AIGeneratedData = generateArticle($scrapedData, $singleSource, true);
        }
        else {
            $AIGeneratedData = generateArticle($scrapedData, $singleSource);
        }

        if($url != null) {
            return $AIGeneratedData['post_url'];
        }
        else {
            return $AIGeneratedData;
        }
    }
}

//check if post exist, and initiate rewriting and posting
function generateArticle($scrapedData, $source, $isFromUrl = false) {
    if (is_array($scrapedData)) {
        $title = $scrapedData['title'];
        $url = $scrapedData['original-url'];


        if($isFromUrl) {
            $published = false;
        }
        else {
            $published = isUrlInPublishedList($url);
        }


        if (!$published) {
            my_second_log('INFO', 'Scraped data success');

            //
            // get AI and post
            //
            $post_id = getAiAndPost($scrapedData, $source); // return post ID

            if($post_id == 0) {
                my_second_log('ERROR', 'An error occured during posting the article, try again.');
                return;
            }

            if ($post_id !== 'error') {
                addToPublishedList($scrapedData['original-url']);

                //add original url to meta
                add_post_meta($post_id, 'original_scr_url', $url, true);

                
                my_second_log('INFO', 'SUCCESS POST posted with ID: ' . $post_id);
                
                
                //get created post url
                $post_url = get_permalink($post_id);
                return array('post_url' => $post_url, 'scraped_url' => $url);
            } else {
                my_second_log('ERROR', 'Failed to process and post article: ' . $url);
            }
        }
        else {
            my_second_log('INFO', 'Skipped, already scraped: ' . $url);
        }
    } else {
        my_second_log('ERROR', 'Invalid scraped data format: ');
    }
}

//get AI article and post, return post_id
function getAiAndPost($scrapedArticle, $source) {
    //
    //get AI ARTICLE
    //
    require_once plugin_dir_path(__DIR__) . '/includes/classes/clsManageRewriting.php';
    $rewritingManager = new clsManageRewriting();
    $aiGeneratedContent = $rewritingManager->generateContentWithAI($scrapedArticle, $source); //assoc array

    
    if (strlen($aiGeneratedContent['content']) < 500) {
        my_second_log('ERROR', 'Content generated by AI too low, post not created for title: ' . $scrapedArticle['title']);
        return;
    }

    //fix AI excerpt fail, take first words of content
    if( $aiGeneratedContent['excerpt'] == null ) {
        $aiGeneratedContent['excerpt'] = getSubstringBeforeFirstDot($aiGeneratedContent['content']);
    }

    // Check if content generation was successful
    if ($aiGeneratedContent === 'error') {
        my_second_log('ERROR', 'Failed to generate content with AI for article: ' . $scrapedArticle['title']);
        return 'error';
    }

    my_second_log('INFO', 'AI content created success');


    //
    // Create a NEW POST with the AI-generated content
    //
    require_once plugin_dir_path(__DIR__) . '/includes/classes/clsPosting.php';
    $posting = new clsPosting();
    return $posting->createNewPost($aiGeneratedContent, $source['categoryId']); // Returns 'success' or 'error'//maybe deprecated
}

